spring:
  data:
    redis:
      host: '192.168.0.11'
      port: 6379
      password: 'redis1234'
  application:
    name: cache-service
eureka:
  client:
    service-url:
      defaultZone: 'http://localhost:8111/eureka/'
server:
  port: 8900